##mysql
MYSQL_ROOT_PASSWORD='rootDBpass#'
MYSQL_DATABASE_HOST='localhost'
MYSQL_DATABASE_HOST_ALIAS='mysqlsre57'
MYSQL_DATABASE_PORT='3306'
MYSQL_DATABASE_USER='dbUser'
MYSQL_DATABASE_PASSWORD='secuDBpass#'
MYSQL_DATABASE_DB='mydb'
